---
title: "Reply to Reviewer #2"
author: 
output:
  bookdown::word_document2:
    fig_caption: yes
    number_sections: no
    global_numbering: true
    reference_docx: word_template.docx
---

# Comments:

**1. All tables and figs: No capitalization of the titles, other than first letter.**
<span style="color:blue"> 
 
+ I modified the titles of all tables and figures.
</span>


**2. Fig, 1. Indicate units for slope and EC in title.**
<span style="color:blue"> 
 
+ I added the explanation about the units of slope and EC in line 131.
</span>


**3. Table 1 and Fig. 3: show units where applicable.**
<span style="color:blue"> 
 
+ I included units in Table 1 and Fig. 3. 
</span>


**4. p. 21 l. 334: For example, instead of using , directly, some some topographical land features and soil properties (remove 1 some)**
<span style="color:blue"> 
 
+ I removed extra "some" from the sentence.
</span>


**5. p. 24: l403 The accuracy of EONR estimation was judged based on the RMSE (/h)of EONR estimation**
<span style="color:blue"> 
 
+ I added indent between "(kg/ha)" and "of"(before: "RMSE (kg/ha)of EONR", after: RMSE (kg/ha) of EONR)
</span>


**6. p. 26 l. 424. To examine whether this problem is a product solely of the specific choice**
<span style="color:blue">  

+ I corrected the grammatical error. Before: "To examine whether this problem is product" to "To examine whether this problem is a product..." 
</span>


**7. P. 29 l 449: Points are clustered much more tightly about the 1-to-1 line much for CF-base than RF and BRF. (remove much)**
<span style="color:blue">  

+ I removed "much" from that sentence.
</span>


**8. Table 3. Provide units.**
<span style="color:blue"> 

+ I added the unit (kg/ha) in the title of Table 3. Similarly, I added units in Table 2, Figure 8, 9, 10, and 11.  
</span>

