---
title: "Reply to Reviewer #1"
author: 
output:
  bookdown::word_document2:
    fig_caption: yes
    number_sections: no
    global_numbering: true
    reference_docx: word_template.docx
---

# Comments:

**1. The first point of the highlight describes the advantages of the CF model over other machine learning methods. The advantages of the CF model are not suitable for the highlight of this study. Therefore, I suggest that the authors revise the first point of the highlight.**
<span style="color:blue">  


</span>


**2. In the second section (lines 76-184), the authors describe the fundamental information necessary to identify EOIR in general and discuss the causal forest approach in detail. The structure of the manuscript is redundant. Some of the descriptions belong to the methods section. Therefore, I suggest that the authors adjust the content of the section. Move some content to the supplement material and others to the methods section.**
<span style="color:blue">  

**Materials and Method to just Method: Monte Carlo Simulations?**

The core objective is to test the CF against existing ML methods. To this core objective, ML simulations are our core method. For this reason, in our Materials and Methods section, we would like to avoid the explanation of how CF works just like we do not give much explanations to any of RF, BRF, and CNN, which are well-established and mostly understood by the reader of this journal. Since, this article is the first to apply CF in the field of agronomy, let alone site-specific input management, we believe that it is worthwhile to present how it works in detail and what conditions are necessary for it to work well. Now, if we place this inside the Materials and Method section, it will break the flow of explaning how MC simulations work, temporarily distracting readers from how MC simulations are conducted to the details of how CF works. Instead of this, we believe that it is beneficial to first give the readers knowledge on how CF works and the potential advantages over the existing predition-oriented ML methods as essential knowledge before we move onto how our MC simulations are conducted in the Materials and Method section, in which we would like to focus on how MC simulations are conducted. 

We talk about identifying site-specific economically optimal input rates in three different places. Therefore, I understand why you feel there are redundancies. However, each of them serves distinctive purposes and we would like to keep the current structure if that is acceptable to you. 

Section 2.1: bluh bluh
Section 3.: true optimal N
Section 3.: estiamted optimal N



</span>

**3. The description of materials and methods section is redundant, please move some unimportant details description to supplementary materials.**

<span style="color:blue">  
We first apologogize that misleading section and subsection titles may have caused confusions about your perceived structural redundancy of this article.

We wrote the initial manuscript with avoiding redundancy in mind and we beleived that we did not have any redundancy in our paper. Therefore, we struggled tremendously to see where the redundancies are. We would really appreciate it if you could specify where you see redundancies and why so that we can address prorperly.

In MC simulation studies, we believe that presenting how data is generated in detail is crucial because the results are dependent on how data is generated. It is much like any emprical studies using real experiment data provides lots of details about the experiemnts. We take reproducibility seriously and we believe that the details we peovided in our manuscript is appropriate. Therefore, we had very hard time telling which is unnecessary and not. We would really appreciate it if you could specify which parts are not critical. 

</span>


**4. What is the unit of the topographical slope？ (line 131)**
<span style="color:blue">  

+ It is degree. <!-- The slope is obtained by dividing the rise over run. If slope is 0.005857921, it means that the field is raised by 0.005857921 m for every 1m you move horizontally.  -->
+ I added the the unit of EC (dS/m) additionally, since another reviewer pointed out the units of EC

</span>


**5. There are 3 numbers in each small frame of Figure 1, please describe the meaning of each number in detail in the figure caption. (line 137)**
<span style="color:blue">  

+ I added the explanation for those numbers in the footnote. 
</span>


**6. Some formulas in the manuscript are not numbered (lines 116, 120, 268, 291, 371, 389).**
<span style="color:blue">  

+ I numbered only referenced equations. Should I number all the equations?
</span>


**7. What are the exact number and proportion of test set training sets? (line 192)**
<span style="color:blue">  

+ I changed this sentence "For each simulated field, we generated a training data set and a validation data set." 

+ The modified version is "After generating one thousand synthetic fields, we repeated to evaluate each of the ML methods by one thousand times. In an individual simulation round, one of the fields was used as a training data set. As a validation data set, a different field from a training data set in that simulation round was used".
</span>


**8. I can’t open the code link (https://github.com/tmieno2/ML_VRA.git, lines 199 and 249) with my browsers (chrome, edge, and Firefox). Please upload the code to the public research data repositories (Zenodo, Mendeley Data, figshare, Harvard Dataverse, etc.), not GitHub. Please generate a separate DOI for your code and cite it.**
<span style="color:blue">  


</span>


**9. Please convert the length units of the manuscript to international length units. (line 207)**
<span style="color:blue">  

+ I converted to those units to meter (m)
  + plot size: 60-ft × 240-ft -> 18.288-m × 73.152-m
  + subplot size: 60-ft × 60-ft -> 18.288-m × 18.288-m
  + plot size: 10-ft × 10-ft -> 3.048-m × 3.048-m
</span>


**10. Please add the number of rows and columns to the plots, subplots, and cells schematics in Figure 2. (line 209)**
<span style="color:blue">  

+ I added the number of rows and columns of plots, subplots and cells in Figure 2. 
</span>


**11. The titles of sections 3.2.1 and 3.2.2 do not provide useful information to the readers, please revise the titles. (lines 342 and 373)**
<span style="color:blue">  

+ Current name:
  + 3.2 OFPE Experiments and Estimating Site-specific Optimal N Rates
    + 3.2.1 RF, BRF, and CNN
    + 3.2.2 CF

+ The title of section 3.2.1: Site-specific EONR estimation by RF, BRF, and CNN
+ The title of section 3.2.1: Site-specific EONR estimation by CF

+ Or, we could change the title of section 3.2 (e.g., Machine Learning Algorithm to Estimate Site-specific EONR) and use the same title for section 3.2.1 and 3.2.2
</span>


**12. The titles of 4.1 and 4.2 are confusing, please revise. (lines 410 and 457)**
<span style="color:blue">  

+ Current name:
  + 4.1 EONR Estimation
  + 4.2 Yield Prediction and EONR Estimation

+ The title of section 4.2 could be changed to "The relationship between the performance of yield prediction and EONR estimation" (?)
</span>

**13. Why there are no CNN results in Figures 8,9, and 10? (lines 439, 441, and 453)**
<span style="color:blue">  

+ I need to add the explanation for it in section 4.1 EONR estimation.  
</span>


**14. I suggest that the authors add to the supplementary material a table of the training accuracy of the different models.**
<span style="color:blue">  

+ run simulations on training dataset, and report the results.
</span>


**15. Please add a separate section for research gaps or uncertainties. Are there any prerequisite assumptions for using the CF model?**
<span style="color:blue">  


</span>


**16. Please revise the conclusion. Most of the content is discussing the uncertainty of the study. Please move the statement about uncertainty to a separate uncertainty section.**

<span style="color:blue">  


</span>

