---
title: "Reply to Reviewer #2"
output:
  bookdown::word_document2:
    fig_caption: yes
    number_sections: no
    global_numbering: true
    reference_docx: ../word_template_format.docx
---

Thank you so much for your comments. By addressing them, we believe the manuscript is improved significantly. Below you will find your comments in bold and our replies in a regular font.

<br>

**1. All tables and figs: No capitalization of the titles, other than first letter.**

<span style="color:blue"> 
We modified all the titles of tables and figures according to your suggestions.
</span>


**2. Fig, 1. Indicate units for slope and EC in title.**

<span style="color:blue"> 
The units of slope and EC are added in the description, which can be found in Appendix A.
</span>


**3. Table 1 and Fig. 3: show units where applicable.**
<span style="color:blue"> 
 
Units are added to the table and figure where applicable. They are now in Appendix C.
</span>


**4. p. 21 l. 334: For example, instead of using , directly, some some topographical land features and soil properties (remove 1 some)**

<span style="color:blue"> 
The extra "some" was removed from the sentence (see p15 l.249).
</span>


**5. p. 24 l. 403: The accuracy of EONR estimation was judged based on the RMSE (/h)of EONR estimation**

<span style="color:blue"> 
The typo was corrected (see p19 l.320). 
</span>


**6. p. 26 l. 424: To examine whether this problem is a product solely of the specific choice**

<span style="color:blue">  
The grammatical error was corrected (see p20 l.340). 
</span>

**7. P. 29 l 449: Points are clustered much more tightly about the 1-to-1 line much for CF-base than RF and BRF. (remove much)**

<span style="color:blue">  
We removed "much" from the sentence (see p24 l.366).
</span>


**8. Table 3. Provide units.**

<span style="color:blue"> 
The unit (kg/ha) was provided in the table (it is now Table 2). Similarly, units are provided to the other result tables.
</span>

