---
title: "Reply to Reviewer #1"
author: Shunkei Kakimoto
output:
  bookdown::word_document2:
    fig_caption: yes
    number_sections: no
    global_numbering: true
    reference_docx: word_template.docx
---

# Comments:

**1. The first point of the highlight describes the advantages of the CF model over other machine learning methods. The advantages of the CF model are not suitable for the highlight of this study. Therefore, I suggest that the authors revise the first point of the highlight.**

<span style="color:blue">  
Yes, we agree with your point, and we have decided to simply drop it from our highlights.

</span>

**2. In the second section (lines 76-184), the authors describe the fundamental information necessary to identify EOIR in general and discuss the causal forest approach in detail. The structure of the manuscript is redundant. Some of the descriptions belong to the methods section. Therefore, I suggest that the authors adjust the content of the section. Move some content to the supplement material and others to the methods section.**
<span style="color:blue">  

We do see a redundancy of expalining how CF can be used to identify site-specific input recommendations. It was explained twice in 2.2 and 3.2.2, while 2.2 is intended for a more general case than 3.2.2 that is specific to our simulations. Therefore, we decided to take out 2.2. We also renamed 2.1 to "Estimating EOIR and Treatment Effects."

We have moved an example of causal tree (previously in seciton 2.3), but decide to keep the explanation of how CF works. The core objective of the paper is to test the CF against existing ML methods in predicting EOIR and economic performance of resulting site-specific input use recommendations. To this core objective, ML simulation is our core method. For this reason, in our Materials and Methods section, we would like to avoid the explanation of how CF works just like we do not give too much explanations to any of RF, BRF, and CNN, which are well-established and mostly understood already by the readers of this journal. However, since this article is the first to apply CF in the field of agronomy, let alone site-specific input management, we believe that it is worthwhile to present how it works in detail and what conditions are necessary for it to work well. Now, if we place such description inside the Materials and Method section, it will break the flow of explaning how MC simulations work, temporarily distracting readers from how MC simulations are conducted to the details of how CF works. Insted, we believe that it is better to first give readers knowledge on how CF works and the potential advantages over the existing predition-oriented ML methods as essential knowledge before we move onto how our MC simulations are conducted in the Materials and Method section, in which we would like to focus on how MC simulations are conducted. Therefore, we kept 2.3 and 2.4 (in the previous round) in the current manuscript.

</span>

**3. The description of materials and methods section is redundant, please move some unimportant details description to supplementary materials.**

<span style="color:blue">  

In rereponse to this comments, we made several changes. 

First, we consolidated 3.1.2 and 3.1.3 in the previous round into a single subsubsection called "Cell-specific Yield Functions and True Economically Optimal N Rates." In doing so, we dropped detailed explanation of the conceptual framework behind the yield response functions based on cell-leve characteristics, $c_i$, and moved it to the supplemnentary appendix (Appendix B). We also removed our detailed description of how parameters and error term were generated and moved it to Appendix C along with relevant tables and figures (spefically table x and figures x, y, z) <span style = "color: blue;"> Shun put table and figure numbers here </span>.

Second, we consolidated 3.1.4 and 3.1.5 in the previous round into a single subsubsection called "Trial Design and Yield Data Generation for Modeling." In doing so, we cut some texts and combined figure x and y in the previous round into a single figure (figure x in the current manuscript).

Third, we removed detailed description of how some parameters are splitted into two parts and moved it to the Appendix.

In MC simulation studies, we believe that presenting how data is generated in detail is crucial because the results are dependent on how data is generated. It is much like any emprical studies using real experiment data provides lots of details about the experiemnts. We take reproducibility seriously and we believe that the details we peovided in our current manuscript is appropriate and it is hard for us to further slim down the section. Moreover, we believe we no longer have any redundancy in this section. 

</span>

**4. What is the unit of the topographical slope？ (line 131)**
<span style="color:blue">  

It is degree. The unit is now provided in the description of the figure in Appendix A. Please not that this example is just for illustrating how CF works.

</span>

**5. There are 3 numbers in each small frame of Figure 1, please describe the meaning of each number in detail in the figure caption. (line 137)**
<span style="color:blue">  

The explanation for those numbers are added as a footnote to the figure (Figure <span style = "color: blue;"> Shun, figure number </span>). 
</span>


**6. Some formulas in the manuscript are not numbered (lines 116, 120, 268, 291, 371, 389).**

<span style="color:blue">  
All the formulas are now numbered. <span style = "color: blue;"> Shun, make sure this happens right before you submit. </span>
</span>


**7. What are the exact number and proportion of test set training sets? (line 192)**
<span style="color:blue">  

We aplogogize that we are not clear on this respect. 

Trainign dataset and test dataset are completely separate. For a given simulation round, training dataset in another round of simulation acts as a "test" dataset. The "test" dataset are created independently from one another and are different in the underdyling field parameters $\alphe$, $\beta$, and $ymax$. Therefor, in MC simulations, a dataset in a given simulation serves as a train data, and served as a test data for another simulation round. The train dataset, however, was split into several parts when cross-validation was performed in determing the optimal hyperparameters within a given simulation round.

We added the following paragraph to section <span style = "color: blue;"> Shun section number here </span> to make this point clear.

"For evaluation of yield and EONR predictions, a dataset from a different simulation round was used as the test dataset. For example, for simulation number 1, train dataset from simulation number 2 was used as the test dataset. This process works because the train datasets were generated by the same data generating process, yet have different underlying field parameters ($\alpha$, $\beta$, $ymax$). Furtehr, each of the "train" datasets are generated independet of one another. Thefore, for a particular simulation round, the dataset in any of the other simualtions can serve as a valid test dataset. This practice avoid creating another set of 1000 simulations fields unnecessarily."

</span>

**8. I can't open the code link (https://github.com/tmieno2/ML_VRA.git, lines 199 and 249) with my browsers (chrome, edge, and Firefox). Please upload the code to the public research data repositories (Zenodo, Mendeley Data, figshare, Harvard Dataverse, etc.), not GitHub. Please generate a separate DOI for your code and cite it.**

<span style="color:blue">  
The simulation codes and the data were also shared on Mendeley Data (<span style = "color: blue;"> Shun, provide the link here </span>) according to the Editor's suggestion for the ease of access. The link is also provided <span style = "color: blue;"> Shun, be speficic about where it is </span>. 

<span style = "color: blue;"> Shun, make sure you cite the code and data. </span>

We realized that the github repository was private and that was why you were not able to access it. We made a public github repository named CF_for_VRA ([here](https://github.com/tmieno2/CF_for_VRA)).
</span>

**9. Please convert the length units of the manuscript to international length units. (line 207)**

<span style="color:blue">  
All the lenth units were converted to meter (m)
</span>

**10. Please add the number of rows and columns to the plots, subplots, and cells schematics in Figure 2. (line 209)**

<span style="color:blue">  
The number of rows and columns of plots, subplots, and cells schematics are now indicated Figure 2.
</span>


**11. The titles of sections 3.2.1 and 3.2.2 do not provide useful information to the readers, please revise the titles. (lines 342 and 373)**

<span style="color:blue">  
We realized that section 3.1 has also a bad title. Therefore, we changed it to "Training Models and Estimating Site-specific EONRs". Further, the title of sections 3.2.1 and 3.2.2 were changed to "Estimation of site-specific EONRs by RF, BRF, and CNN" and "Estimation of site-specific EONRs by CF", respectively. 
</span>


**12. The titles of 4.1 and 4.2 are confusing, please revise. (lines 410 and 457)**

<span style="color:blue">  
The title of 4.1 was changed to "Comparison of EONR estimation accuracy" to reflect its contents. The title of section 4.2 was changed to "The relationship between yield and EONR prediction performances". 
</span>

**13. Why there are no CNN results in Figures 8,9, and 10? (lines 439, 441, and 453)**

<span style="color:blue">  

As explained in section 4.1, CNN failed to predict site-specific EONR because the estimated yield response function were always linear (please see the Table 1). Consequently, I do not think that visualizing the CNN results provide any meaningful implications to understand its performance of EONR estimation performance.

+ I added the explanation for not showing CNN results in Figures 8,9, and 10. ("CNN is not shown as its RMSEs of the EONR estimations and $\hat{\pi}_{def}$ always take $62.8$ kg/ha and \$$58.99$/ha, respectively")
</span>


**14. I suggest that the authors add to the supplementary material a table of the training accuracy of the different models.**

<span style="color:blue">  
+ run simulations on training dataset, and report the results.
</span>


**15. Please add a separate section for research gaps or uncertainties. Are there any prerequisite assumptions for using the CF model?**

<span style="color:blue">  
We added a new section called "Limitations and Future Studies" before the Conclustion section. One of the important assumptions that needs to be satisfied for CF to provides consistent estimation of treatment effects is that the treatment (N rates here) is uncorrelated with unobservable characteristics. Other assumtions are relatively minor. Note that, this is not just for CF, but also for RF, BRF, and CNN. Whenever the variable of interest (N rates here), their estiamtion of its impact on the dependent variable is biased in general. Fortunatley, in OFPE settings, we can randomize or patternize the input rates in a way that the input rates are uncorrelated to the unobserved variables. Therefore, the violation of this assumption is not as much of a concener as in a setting where observational data is used. We discuss these in the "Trial Design and Yield Data Generation for Modeling" section. 
</span>


**16. Please revise the conclusion. Most of the content is discussing the uncertainty of the study. Please move the statement about uncertainty to a separate uncertainty section.**

<span style="color:blue">  
We moved the descriptions of the limitations (uncertainty) of the study to a separate section as mentioned earlier in our reply to your comment 14.
</span>

